project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "Comparing Interpretation Methods for Feature Importance"
  author:
    - Jingxi Li (jl6876)
  repo-url: https://github.com/LargenLi/In-class-demo.git
  date: May 5, 2025
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - DA.qmd
    - Models.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


